# Generated by Django 4.1.1 on 2023-01-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
