# Generated by Django 4.1.1 on 2023-01-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.BigIntegerField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='seller',
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
