# Generated by Django 4.1.1 on 2023-01-06 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_customer_delete_seller_delete_users'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer_tb',
        ),
    ]
