# Generated by Django 4.1.1 on 2023-01-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_customer_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.BigIntegerField()),
                ('address', models.TextField()),
                ('bank_name', models.CharField(max_length=20)),
                ('account_number', models.BigIntegerField()),
                ('ifsc', models.CharField(max_length=10)),
                ('seller_pic', models.ImageField(upload_to='seller/')),
            ],
            options={
                'db_table': 'seller_tb',
            },
        ),
    ]
